language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: ypuqmR0lwNj06cfZA5suKXsLZcyVYtlrPSYDKh2ttrqwD0Erm1LNAAcvy1R1QlsMwbK6RhM6s/+qLjFewvFBzfDEJFZldTVkfNBtXUWv/5zZjif3QGc1ClIr8k05LoRmnZdK6vRahoYdgG2PcGtso0D1kaATz2fxTN1wp0U/9skdn3fmd8/FMTKeWzJk2ObBgv40xRu1BSCMkYfqdRIbI2nXSzgNx7XVcEx98F+l+n3aOcqDu7t/vpUgAgZ/gfVTuau84Fsk7MShWSVLP67peDzetSrvYUO2C9r/uLR3EbESlveva57rjbbHxFuy6np7TYgShSPjVlRh+eg0ubwqgprzpPG0flaX+yeyLwxhFLAqPmu34bwl+lSBE8KJrhbLNvnv2/AIFMS4ASdTd++ZGvmIS0O6CutRwV6+JF4KEaNzCR0YdSmA1J+uQrgNDgTCiLCxnbOx4ODDOE1FYwVtTqvveWF/Dg2TngYqrJsn90pDv4E803e10Q/tG4J/xBBw0b+HofmWnqq5p/JpG9SeC3PZIDRba8cCAOawWKJ0VFe96ywJ5DoXnY1uJPvf3GPY/eqPKfbDlwdrgN7isUbvC7Y24UD+YlM1hq9ueo0n6gADnxlESFVli5DcW/mz/i7XWtLHOhOai1Umi29pVvtylqnAlLXM1k+5uPQq/F7d2ww=
  app: awesome-66
