language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: ks+Vkn1EV1EhVXS17CqheXK7GzyhpzJ3cX1OiGhm75FuNuv2Lq8+9WctS9LX+HjwcMvftIlAvjbb53Osky6IUrBRHU5pHUZmxTtrSX4CrF57bl8Cw7Lb64ixDtgUiEVCOif7aoJIRA1nsFKVgYrybsQ0txu1Y+aNHaHBqeRiwv9dWyBnKWJye5MI8zZPeAq9L04DdyvCKqkM1oAL/GrNIkkC7h/NIwCCR/YEGYoVPUQw6BbkNyHMsqqtQ1l4ARxT2i5gIH4krmmWHGNDEKGffQwwlTVdM7IQd5JLAEpkSPem26v+iYWFcINmEYRR2m05E92RwDccY5fC61mIr3PxoUPzy0tc2m/Zd5UUgDTGMJjabzrF8dAcqleK9NgD7m5NAdtM4h86oc5+dsDDNi+xxjbzpCKY+pmjjfpaYqPhQN2mZTSXfdB9sjlRPoQgMcgtWpDqmU74n0E4OSRpoAL7/dqjvxBs8ICr7rEHGmZl7u+ISaFhB+ihrOZqcKsnEksqERTf6Y4Q+0kJq2y8iJzyohM3NlWJ6EVFWGi0LOmcdx4Qo5RXE4ZweDiXO6mwsMDNdu9/okJ2bzKOD1CxI3Gvm9ag8Wd7zdO5YckKCPQ4RMfpJT7Jxtv5EA7G7D8unZqCYkekYU4uITdTtvEVgSfRwxn0x50eBpNUF6GHwVm9Mt8=
  app: BasicWebApp
