language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 3vj/r7L5Q2GKQLUyDAcveXUA3+GY0Z2PErIK01uvC/ExMa97VKEvWFF5aBg5Oj/6d6H06SnyrI1i+IWxZkU6jABP3TztInCPDvb1mcqUxWRqeciNUz/x5Vw1PR9Q5SDu8frCLMLgH8JpRy3WszgCDwHIEZSCPewUN8xLhvXJkIZ/hsAyWUGoYqzbYVbaFWY6ogf8T36FbOIVe7MuEjqcyI6yRjFHtPCay+bfdLtqEg+uwh/YwlMZ05q6Z4x8/yjOJWyQZ3eZECmReFtEJ0Z4PXsBFyJH38R6bnQsRBWuZz0bYD9cpRxWAst+gR4Cdtl11T1+l7xy4XkECOoVHtWnzEP6mo5zm7Nct++CvW09o6usznW3rId6Il5TkFlPoer1AGf8lVdebxupvKDLX4XbX+62zjxdzOrBiLRV6Z+/X34OmIjrCgJWcC0rkuOEDHnhtk6OvG0uLyS1JlnjQ5bqD5RQfjXLr99ylEW2U5VR4B7lgm89j9PZfAerFAED871bIzM8tJe9QxIYC78ybyFFAjzY/sLDj+LCqsc4YpR42uyakuDnpkjWb5SEU4A3mrnhpcc/ZC/vkQX+samSW5O6jOXy37gf11NjTrUT/UrzK6SY0jFrgcl3TGtn4c2h1VC0tT/7QRID/oFAXhcB1ZC70En/pkjTE/dOV0X/AT6PCl4=
  app: BasicWebApp
